#!/bin/bash

# Installation script for Local RAG
# This will install the 'rag' command so you can run it from anywhere

set -e

echo "🚀 Installing Local RAG system..."
echo ""

# Find where this script is located
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
RAG_SCRIPT="$SCRIPT_DIR/local_rag.py"

echo "📁 Script directory: $SCRIPT_DIR"
echo "📄 Looking for: $RAG_SCRIPT"
echo ""

# Check if local_rag.py exists
if [ ! -f "$RAG_SCRIPT" ]; then
  echo "❌ Error: local_rag.py not found in $SCRIPT_DIR"
  echo ""
  echo "Please make sure local_rag.py is in the same directory as this install script."
  exit 1
fi

echo "✅ Found local_rag.py"
echo ""

# Make local_rag.py executable
chmod +x "$RAG_SCRIPT"
echo "✅ Made local_rag.py executable"

# Create ~/.local/bin directory
mkdir -p "$HOME/.local/bin"
echo "✅ Created $HOME/.local/bin directory"

# Create wrapper script
WRAPPER="$HOME/.local/bin/rag"
cat >"$WRAPPER" <<EOF
#!/bin/bash
# RAG wrapper script
# Auto-generated by install.sh

python3 "$RAG_SCRIPT" "\$@"
EOF

chmod +x "$WRAPPER"
echo "✅ Created wrapper script: $WRAPPER"
echo ""

# Check if ~/.local/bin is in PATH
if [[ ":$PATH:" != *":$HOME/.local/bin:"* ]]; then
  echo "⚠️  $HOME/.local/bin is not in your PATH"
  echo ""

  # Detect shell
  if [ -n "$ZSH_VERSION" ]; then
    SHELL_RC="$HOME/.zshrc"
    SHELL_NAME="zsh"
  elif [ -n "$BASH_VERSION" ]; then
    SHELL_RC="$HOME/.bashrc"
    SHELL_NAME="bash"
  else
    SHELL_RC="$HOME/.profile"
    SHELL_NAME="shell"
  fi

  echo "Adding to PATH in $SHELL_RC..."
  echo "" >>"$SHELL_RC"
  echo "# Added by Local RAG installer" >>"$SHELL_RC"
  echo 'export PATH="$HOME/.local/bin:$PATH"' >>"$SHELL_RC"

  echo "✅ Added to $SHELL_RC"
  echo ""
  echo "🔄 Please run this to activate:"
  echo "   source $SHELL_RC"
  echo ""
  echo "Or close and reopen your terminal."
else
  echo "✅ $HOME/.local/bin is already in your PATH"
fi

echo ""
echo "🎉 Installation complete!"
echo ""
echo "📍 Local RAG script location: $RAG_SCRIPT"
echo "📍 Command wrapper: $WRAPPER"
echo "📍 Data will be stored in: $HOME/.local/share/local_rag/"
echo ""
echo "Usage examples:"
echo "  rag interactive"
echo "  rag ~/Documents/PDFs \"search query\""
echo "  rag index ~/Documents/Textbooks"
echo "  rag list"
echo "  rag ask 'What is dynamic programming?'"
echo ""
echo "💡 Tip: Run 'source $SHELL_RC' or restart your terminal to use the 'rag' command"
echo ""
